name: Auto Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *'  # كل ساعتين
  workflow_dispatch:        # يمكن تشغيله يدويًا من GitHub

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "acmodsffv"
          git config --global user.email "acmodss@gmail.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/souravkl11/raganork-md.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes
        run: |
          git push origin main
